-- Database schema for Workday application
-- Compatible with both MySQL and H2 (for development/testing)
-- Note: H2 uses GENERATED BY DEFAULT AS IDENTITY, MySQL uses AUTO_INCREMENT
-- This schema uses H2 syntax. For MySQL, JPA will handle schema generation automatically.

CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255),
  email VARCHAR(255) UNIQUE,
  password VARCHAR(255),
  role VARCHAR(50),
  work_hours DOUBLE DEFAULT 0.0 NOT NULL
);

CREATE TABLE IF NOT EXISTS company (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_name VARCHAR(255),
  cvr_number VARCHAR(255),
  standard_hourly_rate DOUBLE
);

CREATE TABLE IF NOT EXISTS work_types (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) UNIQUE NOT NULL,
  description VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS projects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description VARCHAR(1024),
  address VARCHAR(255),
  start_date DATE,
  start_time TIME,
  status VARCHAR(50) DEFAULT 'PLANNED',
  priority VARCHAR(50) DEFAULT 'MEDIUM',
  user_id BIGINT,
  work_type_id BIGINT,
  CONSTRAINT fk_projects_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_projects_worktype FOREIGN KEY (work_type_id) REFERENCES work_types(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS material_orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT,
  project_id BIGINT,
  status VARCHAR(50) DEFAULT 'PENDING',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  description VARCHAR(1024),
  CONSTRAINT fk_material_orders_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_material_orders_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_material_orders_user ON material_orders(user_id);
CREATE INDEX IF NOT EXISTS idx_material_orders_created ON material_orders(created_at);

CREATE TABLE IF NOT EXISTS day_plans (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT,
  project_id BIGINT,
  date DATE NOT NULL,
  CONSTRAINT fk_day_plans_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_day_plans_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_day_plans_user_date ON day_plans(user_id, date);

CREATE TABLE IF NOT EXISTS work_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT,
  project_id BIGINT,
  date DATE NOT NULL,
  hours DOUBLE NOT NULL,
  CONSTRAINT fk_work_logs_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_work_logs_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_work_logs_user_date ON work_logs(user_id, date);
